blog/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2020/5/7 19:50
# @Author  : lucky dog
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('posts/<int:pk>/', views.detail, name='detail'),
    path('archives/<int:year>/<int:month>/', views.archive, name='archive'),
    path('categories/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path('tag/<int:pk>', views.tag, name='tag'),
    path('search/', views.search, name='search'),
    path('about', views.about, name='about'),
    path('timeline', views.timeline, name='timeline'),
    path('contact', views.contact, name='contact'),
]

koublog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('blog.urls')),
                  path('', include('comments.urls')),
                  path('', include('message.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

message/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2020/5/17 18:10
# @Author  : lucky dog

from django.urls import path

from . import views

app_name = 'message'
urlpatterns = [
    path('message', views.message, name='message'),
]

message/models.py
from django.db import models

# Create your models here.
from django.utils import timezone


class Message(models.Model):
    name = models.CharField('名字', max_length=50)
    email = models.EmailField('邮箱')
    subject = models.CharField('主题', max_length=50)
    message = models.TextField('消息')
    created_time = models.DateTimeField('创建时间', default=timezone.now)

    class Meta:
        verbose_name = '消息'
        verbose_name_plural = verbose_name
        ordering = ['-created_time']

    def __str__(self):
        return self.name

message/forms.py
# -*- coding: utf-8 -*-
# @Time    : 2020/5/17 18:14
# @Author  : lucky dog

from django import forms
from .models import Message


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['name', 'email', 'subject', 'message']

message/views.py
# Create your views here.
from django.contrib import messages
from django.http import HttpResponse

from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST

from .forms import MessageForm


@require_POST
def message(request):
    # django 将用户提交的数据封装在 request.POST 中，这是一个类字典对象。
    # 我们利用这些数据构造了 CommentForm 的实例，这样就生成了一个绑定了用户提交数据的表单。
    form = MessageForm(request.POST)

    # 当调用 form.is_valid() 方法时，django 自动帮我们检查表单的数据是否符合格式要求。
    if form.is_valid():
        # 检查到数据是合法的，调用表单的 save 方法保存数据到数据库，
        # commit=False 的作用是仅仅利用表单的数据生成 Comment 模型类的实例，但还不保存评论数据到数据库。
        message = form.save(commit=False)

        # 最终将评论数据保存进数据库，调用模型实例的 save 方法
        message.save()

        messages.add_message(request, messages.SUCCESS, '消息发送成功！', extra_tags='success')
        # 重定向到 post 的详情页，实际上当 redirect 函数接收一个模型的实例时，它会调用这个模型实例的 get_absolute_url 方法，
        # 然后重定向到 get_absolute_url 方法返回的 URL。
        return redirect('/contact')
        # return HttpResponse('消息发送成功！')
    # 检查到数据不合法，我们渲染一个预览页面，用于展示表单的错误。
    # 注意这里被评论的文章 post 也传给了模板，因为我们需要根据 post 来生成表单的提交地址。
    # context = {
    #     'form': form,
    # }
    # messages.add_message(request, messages.ERROR, '消息发送失败！请修改表单中的错误后重新提交。', extra_tags='danger')
    # return render(request, 'message/inclusions/preview.html', context=context)

templates/message/inclusions/_form.html
<div class="am-g am-g-fixed blog-fixed blog-content">
    <div class="am-u-sm-12">
        <h1 class="blog-text-center" style="margin: 2rem 0rem 4rem;">-- Contact --</h1>
        <div class="timeline-year">
            <main class="col-md-12">
                        <form action="{% url 'message:message' %}" method="post" class="contact-form">
                          {% csrf_token %}
                            <div class="row">
                                <div class="col-md-6 col-md-offset-3">
                                    <!-- <input type="text" name="name" placeholder="Your Name" required>
                                    <input type="email" name="email" placeholder="Your Email" required>
                                    <input type="text" name="subject" placeholder="Subject" required>
                                    <textarea name="message" rows="7" placeholder="Your Message" required></textarea> -->
                                    <label for="{{ form.name.id_for_label }}">{{ form.name.label }}：</label>
                                    {{ form.name }}
                                    {{ form.name.errors }}
                                    <label for="{{ form.email.id_for_label }}">{{ form.email.label }}：</label>
                                    {{ form.email }}
                                    {{ form.email.errors }}
                                    <label for="{{ form.subject.id_for_label }}">{{ form.subject.label }}：</label>
                                    {{ form.subject }}
                                    {{ form.subject.errors }}
                                    <label for="{{ form.message.id_for_label }}">{{ form.message.label }}：</label>
                                    {{ form.message }}
                                    {{ form.message.errors }}
                                    <button class="btn-send btn-5 btn-5b ion-ios-paperplane" type="submit"><span>Drop Me a Line</span></button>
                                </div>
                            </div>	<!-- row -->
                        </form>
            </main>
        </div>
        <hr>
    </div>
</div>

templates/message/inclusions/preview.html
{% extends 'base.html' %}
{% load message_extras %}

{% block content %}
  {% show_message_form form %}
{% endblock content %}