blog/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2020/5/7 19:50
# @Author  : lucky dog
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('posts/<int:pk>/', views.detail, name='detail'),
    path('archives/<int:year>/<int:month>/', views.archive, name='archive'),
    path('categories/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path('tag/<int:pk>', views.tag, name='tag'),
    path('search/', views.search, name='search'),
    path('about', views.about, name='about'),
    path('timeline', views.timeline, name='timeline'),
    path('contact', views.contact, name='contact'),
]

comments/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2020/5/9 20:40
# @Author  : lucky dog

from django.urls import path

from . import views

app_name = 'comments'
urlpatterns = [
    path('comment/<int:post_pk>', views.comment, name='comment'),
]

koublog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('blog.urls')),
                  path('', include('comments.urls')),
                  path('', include('message.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comments/models.py
from django.db import models
from django.utils import timezone


# Create your models here.

class Comment(models.Model):
    name = models.CharField('名字', max_length=50)
    email = models.EmailField('邮箱')
    url = models.URLField('网址', blank=True)
    text = models.TextField('一字千金')
    created_time = models.DateTimeField('创建时间', default=timezone.now)
    post = models.ForeignKey('blog.Post', verbose_name='文章', on_delete=models.CASCADE)

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name
        ordering = ['-created_time']

    def __str__(self):
        return '{}: {}'.format(self.name, self.text[:20])

comments/forms.py
# -*- coding: utf-8 -*-
# @Time    : 2020/5/9 20:01
# @Author  : lucky dog


from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'url', 'text']

comments/views.py
from django.contrib import messages
from django.shortcuts import render

# Create your views here.

from blog.models import Post
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST

from .forms import CommentForm


@require_POST
def comment(request, post_pk):
    # 先获取被评论的文章，因为后面需要把评论和被评论的文章关联起来。
    # 这里我们使用了 django 提供的一个快捷函数 get_object_or_404，
    # 这个函数的作用是当获取的文章（Post）存在时，则获取；否则返回 404 页面给用户。
    post = get_object_or_404(Post, pk=post_pk)

    # django 将用户提交的数据封装在 request.POST 中，这是一个类字典对象。
    # 我们利用这些数据构造了 CommentForm 的实例，这样就生成了一个绑定了用户提交数据的表单。
    form = CommentForm(request.POST)

    # 当调用 form.is_valid() 方法时，django 自动帮我们检查表单的数据是否符合格式要求。
    if form.is_valid():
        # 检查到数据是合法的，调用表单的 save 方法保存数据到数据库，
        # commit=False 的作用是仅仅利用表单的数据生成 Comment 模型类的实例，但还不保存评论数据到数据库。
        comment = form.save(commit=False)

        # 将评论和被评论的文章关联起来。
        comment.post = post

        # 最终将评论数据保存进数据库，调用模型实例的 save 方法
        comment.save()

        messages.add_message(request, messages.SUCCESS, '评论发表成功！', extra_tags='success')
        # 重定向到 post 的详情页，实际上当 redirect 函数接收一个模型的实例时，它会调用这个模型实例的 get_absolute_url 方法，
        # 然后重定向到 get_absolute_url 方法返回的 URL。
        return redirect(post)

    # 检查到数据不合法，我们渲染一个预览页面，用于展示表单的错误。
    # 注意这里被评论的文章 post 也传给了模板，因为我们需要根据 post 来生成表单的提交地址。
    context = {
        'post': post,
        'form': form,
    }
    messages.add_message(request, messages.ERROR, '评论发表失败！请修改表单中的错误后重新提交。', extra_tags='danger')
    return render(request, 'comments/preview.html', context=context)

templates/comments/inclusions/_form.html
<hr>

<form action="{% url 'comments:comment' post.pk %}" method="post" class="am-form am-g">
    <h3 class="blog-comment">评论</h3>
  <fieldset>
      {% csrf_token %}
    <div class="am-form-group am-u-sm-4 blog-clear-left">
<!--        <input type="text" class="" placeholder="名字">-->
        <label for="{{ form.name.id_for_label }}">{{ form.name.label }}：</label>
        {{ form.name }}
        {{ form.name.errors }}
    </div>
    <div class="am-form-group am-u-sm-4">
<!--      <input type="email" class="" placeholder="邮箱">-->
         <label for="{{ form.email.id_for_label }}">{{ form.email.label }}：</label>
        {{ form.email }}
        {{ form.email.errors }}
    </div>

    <div class="am-form-group am-u-sm-4 blog-clear-right">
<!--      <input type="password" class="" placeholder="网站">-->
        <label for="{{ form.url.id_for_label }}">{{ form.url.label }}：</label>
        {{ form.url }}
        {{ form.url.errors }}
    </div>

    <div class="am-form-group">
<!--      <textarea class="" rows="5" placeholder="一字千金"></textarea>-->
        <label for="{{ form.text.id_for_label }}">{{ form.text.label }}：</label>
        {{ form.text }}
        {{ form.text.errors }}
    </div>

    <p><button type="submit" class="am-btn am-btn-default">发表评论</button></p>
  </fieldset>
</form>

<hr>

templates/comments/inclusions/_list.html
<div >
    <h3 class="blog-comment">评论列表，共 <span>{{ comment_count }}</span> 条评论</h3>
    <ul class="comment-list list-unstyled">
        {% for comment in comment_list %}
        <li class="comment-item">
            <span class="nickname">{{ comment.name }}</span>
            <time class="submit-date" datetime="{{ comment.created_time }}">{{ comment.created_time }}</time>
            <div class="text">
                {{ comment.text|linebreaks }}
            </div>
        </li>
        <hr>
        {% empty %}
        暂无评论！
        {% endfor %}
    </ul>
</div>

templates/comments/inclusions/preview.html
{% extends 'base.html' %}
{% load comments_extras %}

{% block main %}
  {% show_comment_form post form %}
{% endblock main %}