blog/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2020/5/7 19:50
# @Author  : lucky dog
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('posts/<int:pk>/', views.detail, name='detail'),
    path('archives/<int:year>/<int:month>/', views.archive, name='archive'),
    path('categories/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path('tag/<int:pk>', views.tag, name='tag'),
    path('search/', views.search, name='search'),
    path('about', views.about, name='about'),
    path('timeline', views.timeline, name='timeline'),
    path('contact', views.contact, name='contact'),
]

koublog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('blog.urls')),
                  path('', include('comments.urls')),
                  path('', include('message.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
import markdown
from django.utils.html import strip_tags


# Create your models here.
# 在数据库中创建Category表格，列名为name
class Category(models.Model):
    """
        django 要求模型必须继承 models.Model 类。
        Category 只需要一个简单的分类名 name 就可以了。
        CharField 指定了分类名 name 的数据类型，CharField 是字符型，
        CharField 的 max_length 参数指定其最大长度，超过这个长度的分类名就不能被存入数据库。
        当然 django 还为我们提供了多种其它的数据类型，如日期时间类型 DateTimeField、整数类型 IntegerField 等等。
        django 内置的全部类型可查看文档：
        https://docs.djangoproject.com/en/2.2/ref/models/fields/#field-types
        """
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Tag(models.Model):
    """
      标签 Tag 也比较简单，和 Category 一样。
      再次强调一定要继承 models.Model 类！
      """
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Post(models.Model):
    # 文章标题
    title = models.CharField('标题', max_length=100)
    short_title = models.CharField('简写标题', max_length=50, blank=True)

    # 文章正文，使用TextField存储较长文本
    body = models.TextField('正文')

    # 文章创建时间和最后修改时间
    created_time = models.DateTimeField('创建时间', default=timezone.now)
    modified_time = models.DateTimeField('修改时间')

    # 文章摘要，默认CharFiled必须存入数据，指定blank=True将允许空值
    excerpt = models.CharField('摘要', max_length=300, blank=True)

    image = models.ImageField(upload_to='coverimage/%Y/%m/%d/', verbose_name='封面图片', default='coverimage/default.jpg')

    # 文章与分类为一对多关系使用ForeignKey，on_delete表示数据删除时被关联数据的行为，models.CASCADE表示级联删除
    # ManyToManyField表示多对多，文章可以没有标签
    category = models.ForeignKey(Category, verbose_name='分类', on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, verbose_name='标签', blank=True)

    # User是从django.contrib.auth.models导入，文章与作者为一对多关系
    author = models.ForeignKey(User, verbose_name='作者', on_delete=models.CASCADE)

    views = models.PositiveIntegerField(default=0, editable=False)

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-created_time']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.modified_time = timezone.now()
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])
        self.excerpt = strip_tags(md.convert(self.body))[:150]
        self.short_title = strip_tags(md.convert(self.title))[:18]
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    # def image_url(self):
    #     if self.image and hasattr(self.image, 'url'):
    #         return self.image.url
    #     else:
    #     return 'blog/assets/i/f10.jpg'


class Profile(models.Model):

    name = models.CharField(max_length=100)
    text1 = models.TextField('封面简介', blank=True)
    text2 = models.TextField('博客简介', blank=True)
    text3 = models.TextField('关于简介', blank=True)
    image1 = models.ImageField(upload_to='coverimage/', verbose_name='封面图片', default='coverimage/zhixiang1.jpg')
    image2 = models.ImageField(upload_to='coverimage/', verbose_name='博客图片', default='coverimage/zhixiang2.jpg')
    image3 = models.ImageField(upload_to='coverimage/', verbose_name='关于图片', default='coverimage/zhixiang1.jpg')
    class Meta:
        verbose_name = '个人简介'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

blog/views.py
import re

import markdown
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from django.views.generic import ListView, DetailView
from markdown.extensions.toc import TocExtension, slugify
from pure_pagination import PaginationMixin

from .models import Post, Category, Tag, Profile


# def index(request):
#     post_list = Post.objects.all().order_by('-created_time')
#     return render(request, 'blog/lw-index.html', context={'post_list': post_list})

class IndexView(PaginationMixin, ListView):  # ListView从数据库中获取模型列表数据
    model = Post  # 指定获取的模型
    template_name = 'blog/lw-index.html'  # 指定渲染模板
    context_object_name = 'post_list'  # 指定列表数据保存的变量名

    paginate_by = 10


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)

    post.increase_views()

    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
    ])
    post.body = md.convert(post.body)

    m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
    post.toc = m.group(1) if m is not None else ''
    context = {'previous_post': Post.objects.filter(id__lt=pk).first(),
               'next_post': Post.objects.filter(id__gt=pk).last(),
               'post': post}
    # context['previous_post'] = Post.objects.filter(created_time__gt=post.created_time).last()
    # context['next_post'] = Post.objects.filter(created_time__lt=post.created_time).first()
    return render(request, 'blog/lw-article.html', context)


# class PostArticleView(DetailView):
#     # 这些属性的含义和 ListView 是一样的
#     model = Post
#     template_name = 'blog/lw-article.html'
#     context_object_name = 'post'
#
#     def get(self, request, *args, **kwargs):
#         # 覆写 get 方法的目的是因为每当文章被访问一次，就得将文章阅读量 +1
#         # get 方法返回的是一个 HttpResponse 实例
#         # 之所以需要先调用父类的 get 方法，是因为只有当 get 方法被调用后，
#         # 才有 self.object 属性，其值为 Post 模型实例，即被访问的文章 post
#         response = super(PostArticleView, self).get(request, *args, **kwargs)
#
#         # 将文章阅读量 +1
#         # 注意 self.object 的值就是被访问的文章 post
#         self.object.increase_views()
#
#         # 视图必须返回一个 HttpResponse 对象
#         return response
#
#     def get_object(self, queryset=None):
#         # 覆写 get_object 方法的目的是因为需要对 post 的 body 值进行渲染
#         post = super().get_object(queryset=None)
#         md = markdown.Markdown(extensions=[
#             'markdown.extensions.extra',
#             'markdown.extensions.codehilite',
#             # 记得在顶部引入 TocExtension 和 slugify
#             TocExtension(slugify=slugify),
#         ])
#         post.body = md.convert(post.body)
#
#         m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
#         post.toc = m.group(1) if m is not None else ''
#
#         return post


def archive(request, year, month):
    post_list = Post.objects.filter(created_time__year=year,
                                    created_time__month=month
                                    ).order_by('-created_time')
    return render(request, 'blog/lw-index.html', context={'post_list': post_list})


# def category(request, pk):
#     # 记得在开始部分导入 Category 类
#     cate = get_object_or_404(Category, pk=pk)
#     post_list = Post.objects.filter(category=cate).order_by('-created_time')
#     return render(request, 'blog/lw-index.html', context={'post_list': post_list})


class CategoryView(IndexView):

    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)


def tag(request, pk):
    # 记得在开始部分导入 Tag 类
    t = get_object_or_404(Tag, pk=pk)
    post_list = Post.objects.filter(tags=t).order_by('-created_time')
    return render(request, 'blog/lw-index.html', context={'post_list': post_list})


def search(request):
    q = request.GET.get('q')

    if not q:
        error_msg = "请输入搜索关键词"
        messages.add_message(request, messages.ERROR, error_msg, extra_tags='danger')
        return redirect('blog:index')

    post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
    return render(request, 'blog/lw-index.html', {'post_list': post_list})


def about(request):
    return render(request, 'blog/lw-about.html')


def timeline(request):
    post_list = Post.objects.all().order_by('-created_time')
    return render(request, 'blog/lw-timeline.html', context={'post_list': post_list})


def contact(request):
    return render(request, 'blog/lw-contact.html')

templates/blog/inclusions/_archives.html
<div class="blog-clear-margin blog-sidebar-widget blog-bor am-g ">
    <h2 class="blog-title"><span>Archives</span></h2>
    <div class="am-u-sm-12 blog-clear-padding">
        {% for date in date_list %}
            <a href="{% url 'blog:archive' date.year date.month %}" class="blog-tag">{{ date.year }}年{{ date.month }}月</a>
        {% empty %}
        暂无归档！
        {% endfor %}
    </div>
</div>

templates/blog/inclusions/_categories.html
<div class="blog-sidebar-widget blog-bor">
    <h2 class="blog-title"><span>Categories</span></h2>
    <ul class="am-list">
        {% for category in category_list %}
        <li><a href="{% url 'blog:category' category.pk %}">{{ category.name }}<span class="post-count">({{ category.num_posts }})</span></a></li>
        {% empty %}
        暂无分类！
        {% endfor %}
    </ul>
</div>

templates/blog/inclusions/_profile1.html
<div class="blog-sidebar-widget blog-bor">
    <h2 class="blog-text-center blog-title"><span>About ME</span></h2>
    {% for file in profile1_list %}
    <img src="/coverimage/{{ file.image1 }}" alt="about me" class="blog-entry-img" >
    <p>寇志翔</p>
    <p>{{ file.text1|linebreaksbr }}</p>
    {% endfor %}
    <p></p>
</div>

templates/blog/inclusions/_profile2.html
<div class="am-g blog-author blog-article-margin">
    {% for file in profile2_list %}
  <div class="am-u-sm-3 am-u-md-3 am-u-lg-2">
    <img src="/coverimage/{{ file.image2 }}" alt="" class="blog-author-img am-circle">
  </div>
  <div class="am-u-sm-9 am-u-md-9 am-u-lg-10">
  <h3><span>作者 &nbsp;: &nbsp;</span><span class="blog-color">寇志翔</span></h3>
    <p>{{ file.text2 }}</p>
  </div>
    {% endfor %}
</div>

templates/blog/inclusions/_profile3.html
<div class="am-g am-g-fixed blog-fixed blog-content">
    <div class="am-u-sm-12">
        <h1 class="blog-text-center" style="margin: 2rem 0rem 4rem;">-- About Me --</h1>
        {% for file in profile3_list %}
        <div class="timeline-year">
                <ul>
                <img class="" src="/coverimage/{{ file.image3 }}" alt="寇志翔" style="display: block;max-width: 50%;margin: 0 auto;">
                <p style="font-size: 18px;margin: 2rem 0rem;">
                  {{ file.text3 }}
                </p>
                </ul>
        </div>
        {% endfor %}
        <hr>
    </div>
</div>

templates/blog/inclusions/_recent_posts.html
<div class="blog-sidebar-widget blog-bor">
    <h2 class="blog-title"><span>Articles</span></h2>
    <ul class="am-list">
        {% for post in recent_post_list %}
        <li><a href="{{ post.get_absolute_url }}" style="overflow: hidden;
        white-space: nowrap; text-overflow: ellipsis; display: block;">{{ post.title }}</a></li>
        {% empty %}
        暂无文章！
        {% endfor %}
    </ul>
</div>

templates/blog/inclusions/_tags.html
<div class="blog-clear-margin blog-sidebar-widget blog-bor am-g ">
    <h2 class="blog-title"><span>TAG cloud</span></h2>
    <div class="am-u-sm-12 blog-clear-padding">
        {% for tag in tag_list %}
        <a href="{% url 'blog:tag' tag.pk %}" class="blog-tag">{{ tag.name }}</a>
        {% empty %}
        暂无标签！
        {% endfor %}
    </div>
</div>